profiles:
  - name: "development"
    env:
      ANTHROPIC_BASE_URL: "https://api.anthropic.com"
      ANTHROPIC_API_KEY: "sk-ant-api03-..."
      ANTHROPIC_MODEL: "claude-3-5-sonnet-20241022"
      ANTHROPIC_SMALL_FAST_MODEL: "claude-3-haiku-20240307"
    description: "Development environment"
    created: "2024-01-01T00:00:00Z"
    modified: "2024-01-01T00:00:00Z"

  - name: "production"
    env:
      ANTHROPIC_BASE_URL: "https://api.anthropic.com"
      ANTHROPIC_API_KEY: "sk-prod-..."
      ANTHROPIC_MODEL: "claude-3-5-sonnet-20241022"
      ANTHROPIC_SMALL_FAST_MODEL: "claude-3-haiku-20240307"
    description: "Production environment"
    created: "2024-01-01T00:00:00Z"
    modified: "2024-01-01T00:00:00Z"

  - name: "local"
    env:
      ANTHROPIC_BASE_URL: "http://localhost:8056"
      ANTHROPIC_API_KEY: "sk-local-..."
      ANTHROPIC_MODEL: "claude-3-haiku-20240307"
      ANTHROPIC_SMALL_FAST_MODEL: "claude-3-haiku-20240307"
    description: "Local development server"
    created: "2024-01-01T00:00:00Z"
    modified: "2024-01-01T00:00:00Z"

default_profile: "development"